name: Python package

on: [push]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox

      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py

  test-windows:
    runs-on: windows-latest
    env:
      CC: g++ # changing c compiler
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox

      - name: Setting up windows fortran compiler and powershell
        run: echo "[build]`ncompiler=msvc" | Out-File -Encoding ASCII ~/pydistutils.cfg
        shell: powershell

      - name: Run pytest
        # Run tox using the version of Python in `PATH`
        run: pip install -e . && pytest
