name: Python package

on: [push]

jobs:
  test-ubuntu:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: ["3.6"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox==3.20.0

      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox py
