name: Python package

on: [push]

jobs:
  test-ubuntu:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Setup GNU Fortran
        uses: modflowpy/install-gfortran-action@v1
      - name: Install Tox and any other packages
        run: pip install tox==3.24.5 && pip install .

      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
